[package]
name = "Issuer-Hiding_Bobolz"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bls12-381 = "0.5.0"
ark-ec = "0.5.0"
ark-std = "0.5.0"
blake = "2.0.2"
package_name = "0.1.0"
schnorr_pok = "0.20.0"
